# Generated by Django 5.0.4 on 2024-04-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
