# Generated by Django 5.0.4 on 2024-04-19 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='edited_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
